apiVersion: apps/v1
kind: Deployment
metadata:
  name: civic-frontend
  namespace: civic-sense
  labels:
    app: civic-frontend
spec:
  replicas: 2 # Runs 2 copies of your React frontend
  selector:
    matchLabels:
      app: civic-frontend
  template:
    metadata:
      labels:
        app: civic-frontend
    spec:
      containers:
      - name: frontend
        image: abhi754/civicsense-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: civic-frontend-service
  namespace: civic-sense
spec:
  type: NodePort # Exposes the frontend to the public internet
  selector:
    app: civic-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # You will be able to access your app at http://<Worker_IP>:30080
