apiVersion: v1
kind: Secret
metadata:
  name: civic-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://civic:civicSense@cluster0.k0m0w.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "your_super_secret_jwt_key_here"
  ADMIN_SECRET: "admin123"
